import type { Vehicle } from "@/lib/types"

export const vehicles: Vehicle[] = [
  {
    id: "1",
    make: "Lamborghini",
    model: "Aventador",
    year: 2023,
    trim: "SVJ Roadster",
    price: 573966,
    mileage: 1230,
    exteriorColor: "Nero Aldebaran",
    interiorColor: "Nero Ade/Rosso Alala",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "6.5L V12",
    vin: "ZHWUM6ZD9LLA12345",
    stockNumber: "LA23001",
    description:
      "The Lamborghini Aventador SVJ Roadster represents the pinnacle of Italian automotive engineering. This limited-production masterpiece combines breathtaking design with uncompromising performance. The naturally aspirated 6.5L V12 engine delivers an exhilarating 770 horsepower, propelling this exotic from 0-60 mph in just 2.9 seconds. The active aerodynamics system (ALA 2.0) provides exceptional downforce while the open-top experience delivers unfiltered driving emotion. With only 800 examples produced worldwide, this is a rare opportunity to own automotive royalty.",
    features: [
      "6.5L V12 Engine (770 HP)",
      "Lamborghini Dynamic Steering",
      "Carbon Ceramic Brakes",
      "Magnetorheological Suspension",
      "ALA 2.0 Active Aerodynamics",
      "Carbon Fiber Monocoque",
      "Sensonum Premium Sound System",
      "Lamborghini Telemetry System",
      "Alcantara Interior Trim",
      "Forged Composite Carbon Fiber Components",
    ],
    images: [
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Lamborghini/Aventador/9170/1676530772968/front-left-side-47.jpg?imwidth=890&impolicy=resize",
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Lamborghini/Aventador/9170/1676530772968/side-view-(left)-90.jpg?imwidth=890&impolicy=resize",
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Lamborghini/Aventador/9170/1676530772968/rear-left-view-121.jpg?imwidth=890&impolicy=resize",
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Lamborghini/Aventador/9170/1676530772968/front-view-118.jpg?imwidth=890&impolicy=resize",
    ],
    featured: true,
  },
  {
    id: "2",
    make: "Ferrari",
    model: "SF90",
    year: 2022,
    trim: "Stradale",
    price: 625000,
    mileage: 2450,
    exteriorColor: "Rosso Corsa",
    interiorColor: "Nero",
    fuelType: "Hybrid",
    transmission: "Automatic",
    engine: "4.0L V8 Hybrid",
    vin: "ZFF95NLA5M0123456",
    stockNumber: "FS22015",
    description:
      "The Ferrari SF90 Stradale represents the pinnacle of Ferrari technology and performance. This revolutionary hybrid hypercar combines a twin-turbocharged V8 engine with three electric motors to produce a staggering 986 horsepower. The result is breathtaking acceleration from 0-60 mph in just 2.5 seconds and a top speed exceeding 211 mph. The sophisticated all-wheel-drive system and advanced aerodynamics ensure exceptional handling and stability. Inside, the cockpit features a state-of-the-art digital interface and premium materials throughout. This SF90 Stradale is a technological tour de force that defines the future of Ferrari performance.",
    features: [
      "986 HP Hybrid Powertrain",
      "All-Wheel Drive System",
      "eManettino Driving Modes",
      "Carbon Fiber Body Components",
      '16" Curved HD Digital Instrument Cluster',
      "Head-Up Display",
      "Carbon Fiber Racing Seats",
      "Assetto Fiorano Package",
      "Daytona Racing Seats",
      "Carbon Fiber Steering Wheel with LED Shift Lights",
    ],
    images: [
      "https://www.motorshow.me/uploadImages/GalleryPics/305000/B308393-2022-Ferrari-SF90-Stradale--1-.jpg",
      "https://www.motorshow.me/uploadImages/GalleryPics/305000/B308400-2022-Ferrari-SF90-Stradale--8-.jpg",
      "https://www.motorshow.me/uploadImages/GalleryPics/305000/B308396-2022-Ferrari-SF90-Stradale--4-.jpg",
      "https://www.motorshow.me/uploadImages/GalleryPics/305000/B308398-2022-Ferrari-SF90-Stradale--6-.jpg",
    ],
    featured: true,
  },
  {
    id: "3",
    make: "Bugatti",
    model: "Chiron",
    year: 2023,
    trim: "Super Sport",
    price: 3900000,
    mileage: 350,
    exteriorColor: "Atlantic Blue",
    interiorColor: "Beluga Black/French Racing Blue",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "8.0L W16 Quad-Turbo",
    vin: "VF9SPAS15MM795012",
    stockNumber: "BC23007",
    description:
      "The Bugatti Chiron Super Sport represents the absolute pinnacle of automotive engineering and luxury. This extraordinary hypercar features an 8.0-liter quad-turbocharged W16 engine producing an astonishing 1,578 horsepower. Capable of accelerating from 0-60 mph in just 2.4 seconds and reaching a limited top speed of 273 mph, the Chiron Super Sport delivers performance that defies imagination. The exquisite craftsmanship extends throughout the vehicle, from its carbon fiber monocoque to the hand-stitched leather interior. With production limited to just 30 examples worldwide, this is an exceptionally rare opportunity to own one of the most exclusive and technologically advanced automobiles ever created.",
    features: [
      "8.0L Quad-Turbocharged W16 Engine (1,578 HP)",
      "7-Speed Dual-Clutch Transmission",
      "Carbon Ceramic Brakes with Titanium Pistons",
      "Adaptive Chassis",
      "Active Aerodynamics",
      "Telemetry Recording System",
      "Hand-Crafted Interior with Premium Leather",
      "Carbon Fiber Monocoque",
      "Lightweight Magnesium Wheels",
      "Quad LED Headlights with Swarovski Crystals",
    ],
    images: [
      "https://www.netcarshow.com/Bugatti-Chiron_Super_Sport_Golden_Era-2023-1280-849a028e161b2b3bf52db9daf08a7d65f0.jpg",
      "https://www.netcarshow.com/Bugatti-Chiron_Super_Sport_Golden_Era-2023-1280-23eff60a2e2476166efc08f2f051225d8c.jpg",
      "https://www.netcarshow.com/Bugatti-Chiron_Super_Sport_Golden_Era-2023-1280-5eb9465d4ebd457aedea64c87011949ff0.jpg",
      "https://www.netcarshow.com/Bugatti-Chiron_Super_Sport_Golden_Era-2023-1280-520a3e0a53948fe9c812d952906183a12e.jpg",
    ],
    featured: true,
  },
  {
    id: "4",
    make: "Rolls-Royce",
    model: "Phantom",
    year: 2022,
    trim: "Extended Wheelbase",
    price: 535000,
    mileage: 1680,
    exteriorColor: "Diamond Black",
    interiorColor: "Arctic White",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "6.75L V12 Twin-Turbo",
    vin: "SCA685S50MU123456",
    stockNumber: "RR22032",
    description:
      "The Rolls-Royce Phantom Extended Wheelbase represents the ultimate expression of automotive luxury. This magnificent sedan combines timeless design with unparalleled craftsmanship and modern technology. The hand-built 6.75-liter twin-turbocharged V12 engine delivers effortless power with supernatural refinement. The extended wheelbase configuration provides an additional 220mm of rear legroom, creating a palatial interior environment. The starlight headliner, featuring 1,600 hand-placed fiber optic lights, creates a magical ambiance. The 'Gallery' dashboard allows for the display of commissioned artwork behind glass, making each Phantom truly unique. This extraordinary automobile offers an unmatched ownership experience that transcends mere transportation.",
    features: [
      "6.75L Twin-Turbocharged V12 Engine",
      "Satellite-Aided Transmission",
      "Self-Leveling Air Suspension",
      "Starlight Headliner with 1,600 Fiber Optic Lights",
      "Bespoke Audio System with 18 Speakers",
      "Rear Theater Configuration",
      "Picnic Tables with Deployable Monitors",
      "Refrigerated Compartment with Champagne Flutes",
      "Lambswool Floor Mats",
      "Bespoke Interior Commissioned Art Pieces",
    ],
    images: [
      "https://res.cloudinary.com/motortrak/image/upload/t_base_vehicle_transformation/v1706169405/ims2/vehicle-media/b38aa01f4e54891256b29b58f66674be/rolls-royce-Phantom-2022-1/t67fwwmjd7vp6qc7dguv.webp",
      "https://res.cloudinary.com/motortrak/image/upload/t_locator_vehicle_images,w_960/v1706169423/ims2/vehicle-media/b38aa01f4e54891256b29b58f66674be/rolls-royce-Phantom-2022-14/bmhvkccpysonzhmou17p.webp",
      "https://res.cloudinary.com/motortrak/image/upload/t_locator_vehicle_images,w_1600/v1706169431/ims2/vehicle-media/b38aa01f4e54891256b29b58f66674be/rolls-royce-Phantom-2022-19/n4daypqtmafpbtbns9ad.webp",
    ],
    featured: false,
  },
  {
    id: "5",
    make: "McLaren",
    model: "765LT",
    year: 2023,
    trim: "Spider",
    price: 450000,
    mileage: 890,
    exteriorColor: "Papaya Spark",
    interiorColor: "Carbon Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    engine: "4.0L Twin-Turbo V8",
    vin: "SBM15ACA7PW123456",
    stockNumber: "MC23009",
    description:
      "The McLaren 765LT Spider represents the pinnacle of open-top supercar performance. This limited-production masterpiece features a twin-turbocharged 4.0-liter V8 engine producing 755 horsepower, enabling a breathtaking 0-60 mph time of just 2.7 seconds. The lightweight carbon fiber construction, including the innovative Monocage II-S chassis, ensures exceptional rigidity and handling precision. The retractable hardtop can be operated at speeds up to 31 mph, allowing for seamless transitions between coupe-like refinement and open-air exhilaration. With production limited to just 765 units worldwide, this extraordinary vehicle offers exclusivity matched only by its astonishing performance capabilities.",
    features: [
      "4.0L Twin-Turbocharged V8 Engine (755 HP)",
      "7-Speed Seamless Shift Gearbox (SSG)",
      "Active Dynamics Panel with Variable Drift Control",
      "Retractable Hardtop Roof System",
      "Carbon Ceramic Brakes",
      "Lightweight Carbon Fiber Body Panels",
      "Bowers & Wilkins Audio System",
      "McLaren Track Telemetry with Cameras",
      "Ultra-Lightweight 10-Spoke Forged Alloy Wheels",
      "Carbon Fiber Racing Seats",
    ],
    images: [
      "https://static.tcimg.net/vehicles/oem/5b8e2ea418d2bc73/2022-McLaren-765LT.jpg?auto=format&fit=crop&h=514&w=720",
      "https://static.tcimg.net/vehicles/oem/139be99a7bbc12d5/2022-McLaren-765LT.jpg?auto=format&fit=crop&h=255&w=360",
      "https://static.tcimg.net/vehicles/oem/944e325427ddb94c/2022-McLaren-765LT.jpg?auto=format&fit=crop&h=255&w=360",
      "https://static.tcimg.net/vehicles/oem/8b07c7205d92dc89/2022-McLaren-765LT.jpg?auto=format&fit=crop&h=255&w=360",
    ],
    featured: false,
  },
]